source 'https://github.com/CocoaPods/Specs.git'

platform :ios , '7.0'

pod 'Aspects', '~> 1.4.1'
pod 'YTKNetwork', '~> 0.2.0'
pod 'RBStoryboardLink', '~> 0.1.4'
pod 'SVProgressHUD', '~> 1.1.2'

pod 'Olla4iOS', :git => 'https://github.com/nonstriater/Olla4iOS', :branch => 'master'

target :GuitarMasterTests do
    pod 'Expecta', '~> 1.0.0'
end

